# Generated by Django 4.1.7 on 2023-04-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0001_initial'),
        ('account', '0001_initial'),
        ('pubedit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfollower',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.question'),
        ),
        migrations.AddField(
            model_name='articlefollower',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubedit.article'),
        ),
        migrations.AddField(
            model_name='articlefollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='answerfollower',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.answer'),
        ),
        migrations.AddField(
            model_name='answerfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
