# Generated by Django 4.1.7 on 2023-04-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='decription',
            new_name='description',
        ),
    ]
