# Generated by Django 4.1.7 on 2023-04-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='account.user'),
        ),
    ]
