# Generated by Django 4.1.7 on 2023-04-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_last_login_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login_time',
            new_name='login_frequency',
        ),
    ]
