# Generated by Django 4.1.7 on 2023-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_last_login_time_user_login_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_frequency',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
