# Generated by Django 4.1.7 on 2023-04-28 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_login_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_frequency',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
