# Generated by Django 4.1.7 on 2023-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentviewd',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
