# Generated by Django 4.1.7 on 2023-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contentviewd_updated_vote_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
