# Generated by Django 4.1.7 on 2023-04-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.CreateModel(
            name='VideoFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.video')),
            ],
        ),
        migrations.AddConstraint(
            model_name='videofollower',
            constraint=models.UniqueConstraint(fields=('follower', 'video'), name='video_follower'),
        ),
    ]
