# Generated by Django 4.1.7 on 2023-04-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursefollower_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
