# Generated by Django 4.1.7 on 2023-04-24 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofollower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
