# Generated by Django 4.1.7 on 2023-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_videofollower_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
