# Generated by Django 4.1.7 on 2023-04-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioninvitation',
            old_name='reciever',
            new_name='recipient',
        ),
    ]
