# Generated by Django 4.1.7 on 2023-04-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_reciever_questioninvitation_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionfollownotification',
            old_name='anwer',
            new_name='answer',
        ),
    ]
