# Generated by Django 4.1.7 on 2023-04-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_anwer_questionfollownotification_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentFollowNotification',
        ),
    ]
