# Generated by Django 4.1.7 on 2023-04-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_coursefollownotification_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountFollowNotification',
        ),
    ]
