# Generated by Django 4.1.7 on 2023-04-22 08:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('pubedit', '0004_articlefollower_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='feed',
        ),
        migrations.CreateModel(
            name='ArticleFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('feed', tinymce.models.HTMLField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='pubedit.article')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='pubedit.articlefeed')),
                ('poster', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posted', to='account.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
