# Generated by Django 4.1.7 on 2023-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubedit', '0005_alter_article_options_remove_article_feed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefeed',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterField(
            model_name='articlefeed',
            name='feed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
