# Generated by Django 4.1.7 on 2023-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubedit', '0006_alter_articlefeed_options_alter_articlefeed_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeed',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
