# Generated by Django 4.1.7 on 2023-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubedit', '0007_articlefeed_is_pending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='articlefollower',
            options={'ordering': ['-created']},
        ),
    ]
