# Generated by Django 4.1.7 on 2023-04-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answervote',
            table='answer_vote',
        ),
        migrations.AlterModelTable(
            name='questionvote',
            table='question_vote',
        ),
    ]
