# Generated by Django 4.1.7 on 2023-04-05 13:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_answervote_table_alter_questionvote_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feed',
            field=tinymce.models.HTMLField(),
        ),
    ]
