# Generated by Django 4.1.7 on 2023-04-07 05:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_answer_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='votes',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='votes',
            new_name='vote',
        ),
        migrations.AlterField(
            model_name='answer',
            name='feed',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
