# Generated by Django 4.1.7 on 2023-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_questiontag_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
