# Generated by Django 4.1.7 on 2023-04-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_rename_votes_answervote_vote_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answervote',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_vote'),
        ),
    ]
