# Generated by Django 4.1.7 on 2023-04-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_answerfollower_created_questionfollower_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
