# Generated by Django 4.1.7 on 2023-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
