# Generated by Django 4.1.7 on 2023-04-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_alter_answer_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='answerfollower',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
